actions:
  - action: package.install
    provider: paru
    list:
      - zsh
      - fastfetch

  - action: command.run
    command: chsh
    args: ["-s", "/usr/bin/zsh", "{{ user.username }}"]
    privileged: true

  - action: file.copy
    from: .zshrc
    to: "{{ user.home_dir }}/.zshrc"
